docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - "HAL": hal.md
      - "Links and Resources": links-and-resources.md
      - "Generating Resources": resource-generator.md
      - "Custom Resources": cookbook/generating-custom-resources.md
      - "Representations": representations.md
      - "Generating HAL for Doctrine Entities": doctrine.md
      - "Factories": factories.md
    - Cookbook:
        - "Generating Custom Links In Middleware and Request Handlers": cookbook/generating-custom-links-in-middleware.md
        - "Using the ResourceGenerator in path-segregated middleware": cookbook/path-segregated-uri-generation.md
site_name: zend-expressive-hal
site_description: 'Hypertext Application Language for PSR-7 Applications'
repo_url: 'https://github.com/zendframework/zend-expressive-hal'
copyright: 'Copyright (c) 2017-2019 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
