docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
    - Reference:
      - "HAL": hal.md
      - "Links and Resources": links-and-resources.md
      - "Generating Resources": resource-generator.md
      - "Custom Resources": cookbook/generating-custom-resources.md
      - "Representations": representations.md
      - "Factories": factories.md
    - Cookbook:
        - "Generating Custom Links In Middleware": cookbook/generating-custom-links-in-middleware.md
site_name: Hypertext Application Language
site_description: 'Hypertext Application Language for PSR-7 Applications'
repo_url: 'https://github.com/mezzio/mezzio-hal'
